spring:
  application:
    name: microservices-gateway

  cloud:
    gateway:
      routes:
        - id: microservices-users-persons
          uri: lb://microservices-users
          predicates:
            - Path=/api/v1/persons/**
          # filters:
          #   - StripPrefix=1

        - id: microservices-cursos-courses
          uri: lb://microservices-cursos
          predicates:
            - Path=/api/v1/courses/**
          # filters:
          #   - StripPrefix=1

        - id: microservices-cursos-enrollments
          uri: lb://microservices-cursos
          predicates:
            - Path=/api/v1/enrollments/**
          # filters:
          #   - StripPrefix=1

        - id: microservices-exams-exams
          uri: lb://microservices-exams
          predicates:
            - Path=/api/v1/exams/**
          # filters:
          #   - StripPrefix=1

        - id: microservices-exams-questions
          uri: lb://microservices-exams
          predicates:
            - Path=/api/v1/questions/**
          # filters:
          #   - StripPrefix=1
        - id: microservices-payment-payments
          uri: lb://microservices-payments
          predicates:
            - Path=/api/v1/payments/**


server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      microservices-cursos:
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
