spring:
  application:
    name: microservices-exams
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/db_microservices_exams
  cloud:
    loadbalancer:
      ribbon:
        enable: false

server:
  port: 8083

eureka:

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.fasterxml.jackson: DEBUG