spring:
  application:
    name: microservices-payments
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/db_microservices_payments
  cloud:
    loadbalancer:
      ribbon:
        enable: false

server:
  port: 8084

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    org.springframework.cloud.gateway: DEBUG