spring:
  application:
    name: microservices-exams
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_microservices_exams
  cloud:
    loadbalancer:
      ribbon:
        enable: false

server:
  port: 8083

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.fasterxml.jackson: DEBUG